ALTER TABLE public.actions ADD CONSTRAINT action_pkey PRIMARY KEY (action_id);
ALTER TABLE public.actions ADD CONSTRAINT agent_fkey FOREIGN KEY (agent_id) REFERENCES public.agents (agent_id) ON DELETE CASCADE;
ALTER TABLE public.entities ADD CONSTRAINT entity_pkey PRIMARY KEY (entity_id);
ALTER TABLE public.entities ADD CONSTRAINT agent_fkey FOREIGN KEY (agent_id) REFERENCES public.agents (agent_id) ON DELETE CASCADE;
ALTER TABLE public.intents ADD CONSTRAINT intent_pkey PRIMARY KEY (intent_id);
ALTER TABLE public.intents ADD CONSTRAINT agent_fkey FOREIGN KEY (agent_id) REFERENCES public.agents (agent_id) ON DELETE CASCADE;
ALTER TABLE public.expressions ADD CONSTRAINT expression_pkey PRIMARY KEY (expression_id);
ALTER TABLE public.expressions ADD CONSTRAINT intent_fkey FOREIGN KEY (intent_id) REFERENCES public.intents (intent_id) ON DELETE CASCADE;
ALTER TABLE public.messages ADD CONSTRAINT agent_fkey FOREIGN KEY (agent_id) REFERENCES public.agents (agent_id) ON DELETE CASCADE;
ALTER TABLE public.parameters ADD CONSTRAINT parameter_pkey PRIMARY KEY (parameter_id);
ALTER TABLE public.parameters ADD CONSTRAINT expression_fkey FOREIGN KEY (expression_id) REFERENCES public.expressions (expression_id) ON DELETE CASCADE;
ALTER TABLE public.parameters ADD CONSTRAINT entity_fkey FOREIGN KEY (entity_id) REFERENCES public.entities (entity_id) ON DELETE CASCADE;
ALTER TABLE public.responses ADD CONSTRAINT response_pkey PRIMARY KEY (response_id);
ALTER TABLE public.responses ADD CONSTRAINT intent_fkey FOREIGN KEY (intent_id) REFERENCES public.intents (intent_id) ON DELETE CASCADE;
ALTER TABLE public.responses ADD CONSTRAINT action_fkey FOREIGN KEY (action_id) REFERENCES public.actions (action_id) ON DELETE CASCADE;
ALTER TABLE public.synonym_variant ADD CONSTRAINT synonym_fkey FOREIGN KEY (synonym_id) REFERENCES public.synonyms (synonym_id) ON DELETE CASCADE;
ALTER TABLE public.synonyms ADD CONSTRAINT entity_fkey FOREIGN KEY (entity_id) REFERENCES public.entities (entity_id) ON DELETE CASCADE;
ALTER TABLE public.nlu_parse_log ADD CONSTRAINT messages_id_pk FOREIGN KEY (messages_id) REFERENCES messages (messages_id) MATCH FULL ON DELETE CASCADE;
ALTER TABLE public.core_parse_log ADD CONSTRAINT messages_id_pk FOREIGN KEY (messages_id) REFERENCES messages (messages_id) MATCH FULL ON DELETE CASCADE;
